### ISSUE TITLE
dynamic PST

### ISSUE THREAD

**Issue by tissatussa** [FitzOReilly/fatalii#95]
recently i let Fatalii play against many (weak) engines, just to see how it plays. It's still simple but i feel you have a fine approach to construct an engine, so i'm curious ..

you seem to have knowledge about the general search & pruning and concepts like LMR etc .. i'm not very familiar with all those concepts, but i can imagine and read some texts about it. But i was wondering : i guess you're using a PST(s) ? As i understand, these hold some basic reference values for all squares regarding the pieces and their (optimal) movement, and these PSTs are fixed .. what if certain aspects of the position determine a 'custum PST' to use ? Such determining process might even be recursive ?

this is my idea in short, i can elaborate.
just thinking out of the box :-)

![Knight_move](https://user-images.githubusercontent.com/1109281/156090474-9a8091ae-c279-4810-ba90-a7152858ce03.png)

**Comment by FitzOReilly** [comment]
So far, no PSTs are used for the evaluation. Only material and mobility. But I'll add PSTs at some point. I think they can improve the eval significantly and maybe encourage the engine to castle more often and develop the pieces better in the opening :-)

**Comment by tissatussa** [comment]
aha !  I was almost certain any engine would use PSTs .. so, i'm surprised and also delighted : when you're considering PSTs, do you want to think "out of the box" with me ?  The term 'dynamic PST' i invented, i'm not aware such thing is discussed .. the image is a PST art-impression .. can we design / define a PST for each position derived from all piece placements ? eg. upto 6 ply.

**Comment by FitzOReilly** [comment]
I already have my own plans where I want to go with the development of the engine. I'll start with two sets of piece square tables, one for the opening/middlegame and one for the endgame. A lot of engines do that.

I'm also planning to add other evaluation terms such as pawn structure and king safety.

So, for now, I'm not planning to adopt dynamic PSTs.
